Repository sd012gfhkhhvh/Slate.AI, pull requests merged in 2024-01, with the labels that each got.

#15 Removed the background image from join room and RoomPage
  client/src/components/Forms/index.jsx
  client/src/pages/Home/index.css
Labels: bug, good first issue, JWOC, easy

#11 Feature/eraser feature
  client/src/assets/Eraser.png
  client/src/components/WhiteBoard/index.jsx
  client/src/pages/RoomPage/index.jsx
  client/src/socket.js
  server/server.js
Labels: enhancement, JWOC, hard

#12 Updated ui for join/create room page
  client/package-lock.json
  client/src/assets/JoinRoomImage.webp
  client/src/assets/JoinRoomImage.webp:Zone.Identifier
  client/src/assets/canvas-2.png
  client/src/assets/canvas-2.png:Zone.Identifier
  client/src/components/ChatBox/index.css
  client/src/components/Footer/index.css
  client/src/components/Forms/CreateRoomForm/index.css
  client/src/components/Forms/CreateRoomForm/index.jsx
  client/src/components/Forms/JoinRoomForm/index.css
  client/src/components/Forms/JoinRoomForm/index.jsx
  client/src/components/Forms/index.jsx
  client/src/components/Navbar/index.css
  client/src/components/Userbar/index.css
  client/src/components/Userbar/index.jsx
  client/src/components/WhiteBoard/index.jsx
  client/src/pages/Home/index.jsx
  client/src/pages/RoomPage/index.css
  client/src/pages/RoomPage/index.jsx
  client/tailwind.config.js
Labels: enhancement, JWOC, easy

#30 Fixing The Issue of Message Visibility
  client/src/components/ChatBox/index.jsx
  server/server.js
Labels: bug, JWOC, medium
